### ISSUE TITLE
Redundant Code

### ISSUE THREAD

**Issue by aldacron** [DDoS/GBAiD#3]
Before I got distracted by the compilation errors, my purpose was to touch up your extension-checking code. Since I'm unable to compile and test my changes with DMD and I don't feel like installing LDC2 anywhere at the moment, I won't implement a PR for it. I'll just describe it here.

In the DerelictGL3 package there are some global properties you can use to test for extensions. So you can remove your isSupported function from the bottom of gl20.d and replace all extension checks with a simple boolean test. For example, gl20.d line 722 becomes:

```D
if (!GL_EXT_framebuffer_object) {
        throw new Exception("Render buffers are not supported by this hardware");
}
```
This also protects you from the obscure possibility that the driver reports the extension is supported, but Derelict failed to load it -- the property for each extension is set when you call Derelict.reload only if all functions belonging to that extension (if there are any) are successfully loaded.

**Comment by DDoS** [comment]
Fixed in https://github.com/DDoS/GBAiD/commit/8e1577b642cecac38222fab863a4f1a670019533

Thanks.
